version: '2'
services:
  app:
    image: drupal:7.56
    volumes:
      - ./drupal:/var/www/html
      - app-sites:/var/www/html/sites/default
    links:
      - db
      - caddy
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  numberservice:
    build: ./numberservice
    volumes:
      # mount the codebase
      - ./numberservice:/code
      # put node_modules in their own volume for performance
      # and the fact that they won't work if they get shared to
      # the local https://youtu.be/zcSbOl8DYXM?t=14m19s
      - numberservice-deps:/code/node_modules
      - numberservice-data:/code/.tmp
  caddy:
    image: 'abiosoft/caddy'
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - '80:80'
      - '8443:8443'
volumes:
  app-sites:
  numberservice-deps:
  numberservice-data: